### ISSUE TITLE
Help with widescreen

### ISSUE THREAD

**Issue by grd2hid** [itsmeft24/hi-octane-hook#10]
Can you help me with widescreen, like adding a file, or cheat code or something?

**Comment by itsmeft24** [comment]
Add ``EnableWidescreen=TRUE`` to your config.ini (located in Hi-Octane\config.ini) under ``[Boot Config]``. Make sure you have the latest version installed

**Comment by matigkf** [comment]
My game don't run after this my friend

**Comment by matigkf** [comment]
> Add `EnableWidescreen=TRUE` to your config.ini (located in Hi-Octane\config.ini) under `[Boot Config]`. Make sure you have the latest version installed

My game doesn't run after this my friend
