### ISSUE TITLE
Tourists crash the game.

### ISSUE THREAD

**Issue by Jordon87** [itsmeft24/hi-octane-hook#17]
Since the CarsGDF.dll update, getting into exploration mode is a pain. Anytime you try to load in with the tourists added, the game would crash instantly. The only way you can play through exploration is when you delete their lines off their .aty and the game would run smoothly.

I should've added this sometime ago but I think it should be noticed by now.

**Comment by itsmeft24** [comment]
44b20de Fixes some edge cases in the ``fs::FixExtensionReplacement`` patch that were causing the game to crash before entering story mode. Let me know if this fixes it!

**Comment by Jordon87** [comment]
they work now. thanks!
