### ISSUE TITLE
Compiling the source code

### ISSUE THREAD

**Issue by EthanParks25** [itsmeft24/hi-octane-hook#3]
I need help with the source code.

**Comment by itsmeft24** [comment]
The latest commit fixes the GitHub Workflow for auto-building. If you just want the binaries, you no longer need to compile them yourself. Download them from the latest release here: https://github.com/itsmeft24/hi-octane-hook/releases/latest.
(Make sure to rename your DataPC folder to Hi-Octane, and just extract the ``release.zip`` file into the root of the game's installation.)

If you need to compile from source, Visual Studio 2022 should work just fine. You'll need vcpkg to install dependencies, however.
(Make sure you also have the data from ``assets\precompiled.zip`` extracted into the root of the game's installation.)

**Comment by EthanParks25** [comment]
And how do I make the game not crash on startup?

**Comment by EthanParks25** [comment]
Yeah, but every time I try to do it, the game crashes on release build. How could I fix that?
