### ISSUE TITLE
cars-hi-octane-launcher

### ISSUE THREAD

**Issue by grdhid** [itsmeft24/hi-octane-hook#5]
hello, i downloaded your hi octane elements, and pasted them onto my maternational mod, but it crashes while opening it, can you help me, please?

**Comment by itsmeft24** [comment]
Make sure that you renamed your DataPC folder to Hi-Octane before installing hi-octane-hook.

**Comment by grdhid** [comment]
i did it and when i clicked at cars-hi-octane-launcher-cli, it crashes for some reason, can you tell me the solution?
